FROM ubuntu:22.04

MAINTAINER Rajesh 

RUN apt-get update && \
  apt-get install -y wget && \
  wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
  bash Miniconda3-latest-Linux-x86_64.sh   \
  source /root/.bashrc \
  conda config --set auto_activate_base false  \
  conda update -n base -c defaults conda  \
  conda activate cling 
